### ISSUE TITLE
重複使用的 css 可改用 mixin 管理

### ISSUE THREAD

**Issue by shijia22** [shijia22/alpha-shop-vue#1]
> 可以把特定元件會用到的直接寫在 .vue 裡面用 scope 來寫，會更好維護，其他功能性的 style 寫全域沒問題，另外有經常用到的 style 也可以用 mixin 來管理，個別元件要用的時候引入也是種做法

eg:

```css=
/* /src/assets/scss/mixins/list.scss */
@mixin list-pen($icon-size: 1rem, /* other options...*/){
    /* 把 list 前面的點改成鉛筆 icon */
    padding-left: 2rem;
    /* ... */
    li {
        position: relative;
        /* ... */
        &::before {
            content: "";
            position: absolute;
            width: $icon-size;
            height: $icon-size;
            /* ... */
        }
    }
}
```

```htmlembedded=
<!-- /src/components/somePage.vue -->

<template>
    <ul class="list-pencel">
        <li>List item 1</li>
    </ul>
</template>

<style lang="scss" scoped>
@import '@/assets/scss/mixins/list.scss'

.list-pencel{
    @include list-pen(1.5rem);
}
</style>
```
